TripEase/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('b/',include('bookings.urls')),
    path('a/',include('accounts.urls')),
    path('m/',include('merchant.urls')),
    path('t/',include('transport.urls')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("signup/", views.signup_view, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

bookings/urls.py
from django.urls import path
from .views import search_results, travel_list, book_travel, my_bookings, cancel_booking


app_name = 'bookings'

urlpatterns = [
    path("search/", search_results, name="search_results"),
    path("travels/", travel_list, name="travel_list"),
    path("book/<int:travel_id>/", book_travel, name="book_travel"),
    path("my-bookings/", my_bookings, name="my_bookings"),
    path("cancel/<int:booking_id>/", cancel_booking, name="cancel_booking"),
]

core/urls.py
from django.urls import path 
from . import views

app_name = 'core'

urlpatterns = [
    path('',views.home_view,name='home'),
]

merchant/urls.py
from django.urls import path
from . import views

app_name = "merchant"

urlpatterns = [
    path("login/", views.merchant_login_view, name="login"),
    path("logout/", views.merchant_logout_view, name="logout"),
    path("home/", views.merchant_home_view, name="home"),
    path('signup/',views.merchant_signup_view,name='signup'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

# Create your views here.

# create a default home view 
def home_view(request):
    context = {"title": "TripEase"}
    return render(request,"home.html") 

core/templates/partials/footer.html
<footer class="footer mt-auto py-4">
  <div class="container text-center text-white">
    <!-- Logo / Brand -->
    <h5 class="fw-bold mb-2">🚍 TripEase</h5>

    <!-- Links -->
    <div class="mb-2">
      <a href="{% url 'core:home' %}" class="footer-link">Home</a> |
      <a href="#" class="footer-link">About Us</a> |
      <a href="#" class="footer-link">Contact</a> |
      <a href="#" class="footer-link">Terms & Privacy</a>
    </div>

    <!-- Copyright -->
    <small>© {{ now|date:"Y" }} TripEase. All rights reserved.</small>
  </div>
</footer>

core/templates/partials/navbar.html
<nav class="navbar navbar-expand-lg fixed-top shadow-sm">
    <div class="container">
        <a class="navbar-brand fw-bold" href="{% url 'core:home' %}">TripEase</a>
        <button class="navbar-toggler bg-light" type="button" data-bs-toggle="collapse" 
                data-bs-target="#navbarNav" aria-controls="navbarNav" 
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto align-items-lg-center">
                <!-- <li class="nav-item"><a class="nav-link" href="#">Travel Options</a></li> -->
                <li class="nav-item"><a class="nav-link" href="{% url 'bookings:my_bookings' %}">My Bookings</a></li>

                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="#">Welcome, {{ user.username }}</a></li>
                    <li class="nav-item ms-2">
                        <a class="btn btn-danger" href="{% url 'accounts:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
                     <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Sign up</a></li>
                    <!-- <li class="nav-item ms-2">
                        <a class="btn btn-primary" href="{% url 'accounts:signup' %}">Sign Up</a>
                    </li> -->
                    <li class="nav-item ms-2">
                        <a class="btn btn-primary" href="{% url 'merchant:home' %}">Become a Partner</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>